# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


url: http://someshchaturvedi.github.io/
baseurl: /
title: Somesh Chaturvedi
author: Somesh Chaturvedi
description: Personal blog and resume
avatar: somesh2.jpg
email: schaturvedi@bt.iitr.ac.in
github: someshchaturvedi
twitter: somesh0828
linkedin: username
medium: somesh.08.96
facebook: Somesh-Chaturvedi/100004797498916

collections:
    - projects
